// Array of every ore name, alphabetically sorted
export const OreNames = [
    "Abyssal Sludge", "Adamantite", "Adrenilar", "Aetherice", "Ailmentin", 
    "Alkanite", "Aluminum", "Amber", "Ambrosine", "Amethyst", "Amnesite", 
    "Andrium", "Anetrium", "Antimatter", "Antireal", "Apiastrine", "Aquamarine", 
    "Argibar", "Arkivyll", "Astathian", "Asthenocrit", "Astratine", "Auricallium", 
    "Aurorum", "Axion", "Barium", "Bedrock", "Bismuth", "Blastium", "Blue Ice", 
    "Boomite", "Boron", "Bottom Quark", "Cadmium", "Caesium", "Carnelian", "Celesteel", 
    "Centriale", "Chalcedony", "Charm Quark", "Chlorophyte", "Chromium", "Chronon", 
    "Chrysoprase", "Cindrasil", "Cinnabar", "Coal", "Cobalt", "Cometite", 
    "Constellatium", "Convectine", "Copper", "Corium", "Coronium", "Corrodoil", 
    "Cosmaline", "Cosmic Glass", "Cosmodium", "Crimstone", "Cryonine", "Cryoplasm", 
    "Crystal Photon", "Crystalline Plasma", "Cytosol", "Dark Energy", "Dark Matter", 
    "Demonite", "Desmentinum", "Diamond", "Down Quark", "Dragonglass", "Dystranum", 
    "Ebonakite", "Eclipsium", "Ectokelyte", "Egg", "Eidoliphyll", "Electrium", "Element V", 
    "Emerald", "Enceladrum", "Endotravine", "Equilibrium", "Ethanerite", "Evrasalt", "Exodian", 
    "Exotic Matter", "Fabric", "Ferozium", "Firecrystal", "Formicite", "Frightstone", 
    "Frostarium", "Frozen Nitrogen", "Gallium", "Galvanium", "Gargantium", "Garnet", 
    "Geometrium", "Glowstone", "Gluonium", "Gold", "Graphene", "Graviton", "Gray Matter", 
    "Grimstone", "Gyrivarium", "Hadronil", "Havicron", "Hellstone", "Hematite", "Hexflame", 
    "Hollevite", "Horrorstone", "Hydrolyth", "Hyperium", "Ichor", "Impervium", "Infernilus", 
    "Infrarian", "Inversium", "Iridium", "Iron", "Isoronil", "Jade", "Jalaboño", "Jasper", 
    "Kafsium", "Korenil", "Korundum", "Krazmite", "Kryposilus", "Kyanite", "Lapis", "Lead", 
    "Leptonyte", "Liquid Gold", "Lithium", "Lumenyl", "Macusmite", "Magmium", "Magnesium", 
    "Magnetite", "Malachite", "Malbrane", "Mantle Fragment", "Mauraline", "Mavrikine", 
    "Mesmirian", "Mesonyte", "Meteorite", "Mezihyrium", "Mithril", "Molten Iron", 
    "Moonstone", "Myriroule", "Naquadah", "Navitalc", "Nebulinite", "Neptunium", 
    "Nerolin", "Nethrastine", "Neuroplast", "Neutrine", "Neutrino", "Neutronium", 
    "Newtonium", "Nickel", "Nihinoris", "Nilidust", "Noise", "Null", 
    "Nyrvinoris", "Obliviril", "Ochistrite", "Ogleum", "Onyx", "Opal", "Orichalican", 
    "Osmium", "Palladium", "Panolethrium", "Pearl", "Peridot", "Periglise", "Perilium", 
    "Phantasmorite", "Phosphyll", "Photalizine", "Plasma", "Platinum", "Plutonium", 
    "Polarveril", "Polonium", "Positron", "Primordian", "Prismaline", "Profelis", 
    "Protireal", "Protonium", "Pyroplasm", "Pyroscorium", "Quark Matter", "Quicksilver", 
    "Qylicryst", "Radium", "Rainbonite", "Raw Energy", "Redsteel", "Reithum", 
    "Rhylazil", "Rifted Barrier", "Rimrock", "Rose Quartz", "Ruby", "Samarium", 
    "Sapphire", "Scorched Bedrock", "Shadow Quartz", "Shadowspec", "Silver", 
    "Sinfurmium", "Singularity", "Soimabarium", "Solarium", "Soul Crystal", 
    "Spiralium", "Stardust", "Starniferus", "Starsteel", "Stellar Sediment", 
    "Stellarite", "Stone", "Strange Matter", "Strange Quark", "Stratocrit", 
    "String", "Sulfur", "Sunstone", "Supermatter", "Surrenderock", "Tachyon", 
    "Taynalum", "Technetium", "Tellurium", "Tendrock", "Tenebris", "Territane", 
    "Tetraquark", "Thallium", "Thermisine", "Thorium", "Thulinyl", "Titanium", 
    "Top Quark", "Topaz", "Torn Fabric", "Toxirock", "Trinasine", "Tritium", 
    "Truth Quark", "Tungsten", "Ubriniale", "Ultranium", "Universal Barrier", 
    "Universallium", "Unobtainium", "Up Quark", "Uranium", "Vanadium", "Vantaslate", 
    "Verglazium", "Vermillium", "Vicious Shard", "Void Orb", "Vorazylith", "Vrimsten", 
    "Vythusilyte", "Wish Alloy", "Xerutherum", "Yilantibris", "Yunium", "Zeronian", 
    "Zetaslime", "Zilithorus", "Zinc", "Zynulvinite"
];